### ISSUE TITLE
[Вопрос] Покупка

### ISSUE THREAD

**Issue by nagayev** [samgozman/tinkoff-api-securities#1]
А купить из этого списка что-то можно?

**Comment by samgozman** [comment]
Да, конечно! Это список торгуемых инструментов у брокера Тинькофф для обычных инвесторов.
Сделал для себя в виде отдельной либы, тк в нескольких проектах используется в качестве фильтра

**Comment by nagayev** [comment]
@samgozman Т.е это удобная обертка над Тинькофф апи?

**Comment by samgozman** [comment]
По сути да

**Comment by nagayev** [comment]
@samgozman Понял, спасибо.
P.S Yoptascript рулит
